defmodule Hexling.Message do
  @moduledoc """
  Defines a Message which is sent to the LLM server
  """

  defstruct [:type, :content]

  @type t :: %__MODULE__{}

  @doc """
  A message sent by a human using the tool
  """
  @spec human(String.t()) :: t()
  def human(content) do
    %__MODULE__{type: "human", content: content}
  end

  @doc """
  A message generated by the AI
  """
  @spec ai(String.t()) :: t()
  def ai(content) do
    %__MODULE__{type: "ai", content: content}
  end

  @doc """
  A message used to prime the AI
  """
  @spec system(String.t()) :: t()
  def system(content) do
    %__MODULE__{type: "system", content: content}
  end

  @doc """
  A generic chat message
  """
  @spec chat(String.t()) :: t()
  def chat(content) do
    %__MODULE__{type: "chat", content: content}
  end
end
